services:
  db:
    image: postgres:16-alpine # Usamos a versão 16 do PostgreSQL, leve
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # Mapeia a porta do container para a porta da sua máquina
    volumes:
      - db-data:/var/lib/postgresql/data # Persiste os dados do banco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data: