services:
  db:
    image: postgres:16-alpine # Usamos a versão 16 do PostgreSQL, leve
    restart: always
    environment:
      POSTGRES_DB: WDLD_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: UmaSenhaMuitoBoaParaUmSiteMuitoBom!
    ports:
      - "5432:5432" # Mapeia a porta do container para a porta da sua máquina
    volumes:
      - db-data:/var/lib/postgresql/data # Persiste os dados do banco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d WDLD_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data: